In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Uppgift 3

In [2]:
def func(t):
    Q = 9 + 5*(np.cos(0.4*t))**2
    return Q

def fun(t):
    c = 5*(np.e**(-0.5*t)) + 2*(np.e**(0.15*t))
    return c

def f(t): #Definierar funktionen som Q*c
    return func(t) * fun(t)

a) Skriv ett Python-program som approximerar värdet av integralen (5) med trapetsregeln. Börja med fyra delintervall (N = 4) och dubbla antalet delintervall tills dess att integralvärdet har 3 säkra decimaler. Programmet ska skriva ut en tabell med värdena på N samt motsvarande integralvärden. Programmet ska även beräkna och skriva ut metodens noggrannhetsordning (använd dina beräknad integralvärden

In [3]:
#Trapetsregeln
a = 3 # Nedre integrationsgränsen 
b = 9 # Övre integrationsgränsen 
N = 4 # Steglängd 
h = 1/4 

def trapz(a,b,N):
    #Trapetsregeln
    h = (b-a)/N # Antal intervall 
    x = np.linspace(a,b,int(N)+1) # Skapa en vektor med integrationspunkter 
    fx = f(x) # Räkna ut funktionen i integrationspunkterna
    Th = h*(np.sum(fx)-0.5*(fx[0]+fx[-1]))
    return Th

diff = 1000
print('{:<4}{:>20}{:>20}'.format('N','t1','diff')) #Printar en header till tabellen
while diff>1E-3: #Fortsätter beräkna medan diffen är större än vår tolerans(3 säkra decimaler)
    t1 = trapz(a, b, N)
    N = N*2
    t2 = trapz(a, b, N)
    diff = t1-t2
    print('{:<4}{:>20f}{:>20f}'.format(N,t1,diff)) #Ger datan i tabelliknande lista

print('') #spacer
Thvec = np.empty(5)

for i in range(5):
    N = (b-a)/h 
    x = np.linspace(a,b,int(N)+1) # Skapa en vektor med integrationspunkter 
    fx = f(x) # Räkna ut funktionen i integrationspunkterna
    Th = h*(np.sum(fx)-0.5*(fx[0]+fx[-1]))
    Thvec[i] = Th # Spara integralvärdet
    h = h/2 # halvera h 
    
Upper = np.abs(Thvec[1:-1] - Thvec[0:-2])
Lower = np.abs(Thvec[2:] - Thvec[1:-1])
kvot = Upper/Lower
print("Kvoten:","\n", kvot)
print("Integralen:","\n", Thvec)
print("Feluppskattning:","\n", np.abs(Thvec[-2]-Thvec[-1]))

N                     t1                diff
8             390.294794            1.239238
16            389.055557            0.313675
32            388.741881            0.078667
64            388.663214            0.019683
128           388.643532            0.004922
256           388.638610            0.001230
512           388.637379            0.000308

Kvoten: 
 [3.99858632 3.99964638 3.99991158]
Integralen: 
 [388.6836189  388.64863499 388.63988592 388.63769846 388.63715159]
Feluppskattning: 
 0.0005468771959158403


c) Utöka programmet så att det även approximerar värdet av integralen (5) med Simpsons formel. Börja med fyra delintervall (N = 4) och dubbla antalet delintervall tills dess att integralvärdet har 3 säkra decimaler. Programmet ska även i det här fallet skriva ut en tabell med värdena på N samt motsvarande integralvärden. Beräkna och skriva ut metodens noggrannhetsordning.

In [4]:
#Simpsons regel
a = 3 #Nedre integrationsgräns
b = 9 #Övre integrationsgräns
N = 4 #Steglängd
def simps(a, b, N): #Definierar Simpsons regel
    h = (b-a)/N
    x = np.linspace(a,b,N+1)
    y = f(x)
    Sh = h/3 * np.sum(y[0:-1:2] + 4*y[1::2] + y[2::2])
    return Sh

diff = 1000
print('{:<4}{:>20}{:>20}'.format('N','t1','diff')) #Printar en header till tabellen
while diff>1E-3: #Fortsätter beräkna medan diffen är större än vår tolerans(3 säkra decimaler)
    t1 = simps(a, b, N)
    N = N*2
    t2 = simps(a, b, N)
    diff = t1-t2
    print('{:<4}{:>20f}{:>20f}'.format(N,t1,diff)) #Ger datan i tabelliknande lista
    
print('') #Spacer 
Shvec=np.empty(4) # Tom vektor med 4 "platser", detta pga 3 säkra decimaler.
N = 4 #Antal intervall 
for i in range(4):
    h = (b-a)/N 
    x = np.linspace(a,b,N+1) # Skapa en vektor med integrationspunkter 
    fx = f(x) # Räkna ut funktionen i integrationspunkterna
    Sh = h/3*(fx[0] + 4*np.sum(fx[1:N:2]) + 2*sum(fx[2:N-1:2]) + fx[N]) #Simpsons regel
    Shvec[i] = Sh # Spara integralvärdet
    N = 2*N # Dubblera antal intervall 
    
Upper = np.abs(Shvec[1:-1] - Shvec[0:-2])
Lower = np.abs(Shvec[2:] - Shvec[1:-1])
kvot = Upper/Lower
print("Kvoten:","\n", kvot)
print("Integralen:","\n", Thvec)
print("Feluppskattning:","\n", np.abs(Thvec[-2]-Thvec[-1]))

N                     t1                diff
8             388.709142            0.066664
16            388.642478            0.005155
32            388.637323            0.000332

Kvoten: 
 [12.93311655 15.54809479]
Integralen: 
 [388.6836189  388.64863499 388.63988592 388.63769846 388.63715159]
Feluppskattning: 
 0.0005468771959158403
